Config = Config or {}

Config.RosterLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
    ['sast'] = '',
    ['sasp'] = '',
    ['doc'] = '',
    ['lssd'] = '',
    ['sapr'] = '',	
}


Config.UseWolfknightRadar = false
Config.WolfknightNotifyTime = 5000 --How long the notification displays for in milliseconds (30000 = 30 seconds)
--[[
Adds support for Wraith ARS 2X by WolfKnight98 (wk_wars2x)
https://github.com/WolfKnight98/wk_wars2x
To save on unnecessary database queries, in wk_wars2x/config.lua set 'CONFIG.use_sonorancad = true'
This will only check plates of vehicles that have been occupied by a player
--]]

Config.OnlyShowOnDuty = true

Config.Fuel = "LegacyFuel" -- "LegacyFuel", "lj-fuel"

Config.PenalCodeTitles = {
    [1] = 'INFRAÇÕES DE TRÂNSITO',
    [2] = 'CRIMES LEVES',
    [3] = 'CRIMES MÉDIOS',
    [4] = 'CRIMES GRAVES',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Abuso excessivo da buzina', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 1', months = 0, fine = 100, color = 'green'},
        [2] = {title = 'Andar sem Capacete (Moto)', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 2', months = 0, fine = 150, color = 'green'},
        [3] = {title = 'Acidente e Fuga', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 3', months = 7, fine = 2100, color = 'red'},
        [4] = {title = 'Conduzir em Sentido Contrário', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 4', months = 0, fine = 500, color = 'green'},
        [5] = {title = 'Condução Fora da Via de Trânsito', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 5', months = 0, fine = 250, color = 'green'},
        [6] = {title = 'Conduzir sem Habilitação Legal', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 6', months = 5, fine = 1500, color = 'red'},
        [7] = {title = 'Condução Desordeira', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 7', months = 0, fine = 650, color = 'green'},
        [8] = {title = 'Estacionamento Proibido', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 8', months = 0, fine = 150, color = 'green'},
        [9] = {title = 'Exceder os 50km/h', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 9', months = 0, fine = 300, color = 'green'},
        [10] = {title = 'Exceder os 70km/h', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 10', months = 0, fine = 600, color = 'green'},
        [11] = {title = 'Exceder os 90km/h', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 11', months = 0, fine = 800, color = 'orange'},
        [12] = {title = 'Exceder os 120km/h', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 12', months = 0, fine = 1000, color = 'orange'},
        [13] = {title = 'Falta de decumentos ', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 13', months = 0, fine = 800, color = 'orange'},
        [14] = {title = 'Falta de Seguro', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 14', months = 0, fine = 1000, color = 'red'},
        [15] = {title = 'Falta de Inspeção', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 15', months = 0, fine = 500, color = 'green'},
        [16] = {title = 'Mudança de Direção Proibida', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 16', months = 0, fine = 200, color = 'green'},
        [17] = {title = 'Modificações Ilegais', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 17', months = 0, fine = 400, color = 'orange'},
        [18] = {title = 'Não parar ao Sinal de STOP', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 18', months = 0, fine = 250, color = 'green'},
        [19] = {title = 'Não parar no Sinal Luminoso Vermelho', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 19', months = 0, fine = 300, color = 'green'},
        [20] = {title = 'Passagem da Linha Longitudinal', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 20', months = 0, fine = 250, color = 'green'},
        [21] = {title = 'Ruido Excessivo de Veiculo', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 21', months = 0, fine = 350, color = 'green'},
        [22] = {title = 'Ultrapassagem Proibida', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 22', months = 0, fine = 350, color = 'green'},
        [23] = {title = 'Uso de Neons ', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 23', months = 0, fine = 300, color = 'green'},
        [24] = {title = 'Vidros Totalmente Fumados', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 24', months = 0, fine = 250, color = 'green'},
        [25] = {title = 'Veiculo que não esta perfeito para circular', class = 'Infrações de Trânsito', id = 'Infraçao da lei Nº 1 alinea 25', months = 0, fine = 500, color = 'orange'},
    },
    [2] = {
        [1] = {title = 'Ameaçar Civis', class = 'Crimes Leves', id = 'Infraçao da lei Nº2 alinea 1', months = 0, fine = 2000, color = 'green'},
        [2] = {title = 'Ameaçar as Forças de Segurança', class = 'Crimes Leves', id = 'Infraçao da lei Nº2 alinea 2', months = 0 , fine = 2000, color = 'red'},
        [3] = {title = 'Cúmplice em Crime', class = 'Crimes Leves', id = 'Infraçao da lei Nº2 alinea 3', months = 5, fine = 2500, color = 'red'},
        [4] = {title = 'Condução sobre efeito de Alcool', class = 'Crimes Leves', id = 'Infraçao da lei Nº2 alinea 4', months = 12, fine = 2500, color = 'green'},
        [5] = {title = 'Desrespeitar as Forças de Segurança', class = 'Crimes Leves', id = 'Infraçao da lei Nº2 alinea 5', months = 0, fine = 1500, color = 'orange'},
        [6] = {title = 'Insultar Cívis', class = 'Crimes Leves', id = 'Infraçao da lei Nº2 alinea 6', months = 0, fine = 1000, color = 'green'},
        [7] = {title = 'Insultar as Forças de Segurança', class = 'Crimes Leves', id = 'Infraçao da lei Nº2 alinea 7', months = 0, fine = 1500, color = 'orange'},
    },
    [3] = {
        [1] = {title = 'Agressão Fisica', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 1', months = 20, fine = 6000, color = 'orange'},
        [2] = {title = 'Colheita de Estupefacientes', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 2', months = 20, fine = 6000, color = 'orange'},
        [3] = {title = 'Corrupção', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 3', months = 20, fine = 6000, color = 'orange'},
        [4] = {title = 'Fornecer Informação Incorreta', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 4', months = 15, fine = 4500, color = 'orange'},
        [5] = {title = 'Fuga ao fisco', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 5', months = 25, fine = 7500, color = 'orange'},
        [6] = {title = 'Intimidação', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 6', months = 15, fine = 4500, color = 'orange'},
        [7] = {title = 'Lavagem de Dinheiro', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 7', months = 25, fine = 7500, color = 'orange'},
        [8] = {title = 'Obstrução a Justiça', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 8', months = 25, fine = 7500, color = 'orange'},
        [9] = {title = 'Posse de Arma de Fogo sem Licença', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 9', months = 15, fine = 4500, color = 'orange'},
        [10] = {title = 'Posse de Dinheiro Sujo', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 10', months = 20, fine = 6000, color = 'orange'},
        [11] = {title = 'Posse de Estupefacientes', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 11', months = 20, fine = 6000, color = 'orange'},
        [12] = {title = 'Resistência a Detenção', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 12', months = 20, fine = 6000, color = 'orange'},
        [13] =  {title = 'Roubo de Veiculo', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 13', months = 15, fine = 4500, color = 'orange'},
        [14] = {title = 'Roubo de viatura do estado', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 14', months = 20, fine = 6000, color = 'orange'},
        [15] = {title = 'Suborno', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 15', months = 15, fine = 4500, color = 'orange'},
        [16] = {title = 'Tentativa de Assalto a Civil', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 16', months = 15, fine = 4500, color = 'orange'},
        [17] = {title = 'Tentativa de fuga a policia', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 17', months = 25, fine = 7500, color = 'orange'},
        [18] = {title = 'Trafico de Estupefacientes', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 18', months = 28, fine = 8400, color = 'orange'},
        [19] = {title = 'Tratamento de Estupefacientes', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 19', months = 25, fine = 7500, color = 'orange'},
        [20] = {title = 'Uso Negligente de Arma', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 20', months = 10, fine = 3000, color = 'orange'},
        [21] = {title = 'Venda de Estupefacientes', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 21', months = 29, fine = 8700, color = 'orange'},
        [22] = {title = 'Venda de Informações Ilegais', class = 'Crimes Médios', id = 'Infraçao da lei Nº3 alinea 22', months = 25, fine = 7500, color = 'orange'},
    },
    [4] = {
        [1] = {title = 'Afiliação a Redes Criminosas', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 1', months = 35, fine = 10500, color = 'red'},
        [2] = {title = 'Agressão as Forças de Segurança', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 2', months = 35, fine = 10500, color = 'red'},
        [3] = {title = 'Agressão com Arma Branca', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 3', months = 30, fine = 9000, color = 'orange'},
        [4] = {title = 'Agressão com Arma de Fogo', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 4', months = 35, fine = 10500, color = 'red'},
        [5] = {title = 'Ameaça de Caracter Terrorista', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 5', months = 45, fine = 13500, color = 'red'},
        [6] = {title = 'Assalto a Entidade Bancaria', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 6', months = 45, fine = 13500, color = 'red'},
        [7] = {title = 'Assalto a joalharia ', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 7', months = 45, fine = 13500, color = 'orange'},
        [8] = {title = 'Assalto a lojas ', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 8', months = 40, fine = 12000, color = 'orange'},
        [9] = {title = 'Assalto a Residencia', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 9', months = 40, fine = 12000, color = 'orange'},
        [10] = {title = 'Assalto Civil', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 10', months = 35, fine = 10500, color = 'red'},
        [11] = {title = 'Atos de Caracter Terrorista', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 11', months = 50, fine = 15000, color = 'red'},
        [12] = {title = 'Distribuição Ilegal de Armas', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 12', months = 35, fine = 10500, color = 'red'},
        [13] = {title = 'Fuga da prisao ', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 13', months = 35, fine = 9000, color = 'red'},
        [14] = {title = 'Fugir as Forças de Segurança', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 14', months = 40, fine = 12000, color = 'red'},
        [15] = {title = 'Homicidio a uma Força de Segurança', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 15', months = 60, fine = 18000, color = 'red'},
        [16] = {title = 'Homicidio com Dolo', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 16', months = 60, fine = 18000, color = 'red'},
        [17] = {title = 'Homicidio por Negligência', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 17', months = 40, fine = 12000, color = 'red'},
        [18] = {title = 'Posse de Explosivos', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 18', months = 30, fine = 9000, color = 'red'},
        [19] = {title = 'Rapto', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 19', months = 40, fine = 12000, color = 'red'},
        [20] = {title = 'Tentativa de fuga da Prisão ', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 20', months = 30, fine = 9000, color = 'red'},
        [21] = {title = 'Tentativa de Homicidio', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 21', months = 40, fine = 12000, color = 'red'},
        [22] = {title = 'Tenta. de Homicidio à Força de Segurança', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 22', months = 45, fine = 13500, color = 'red'},
        [23] = {title = 'Tráfico de Armas', class = 'Crimes Graves', id = 'Infraçao da lei Nº4 alinea 23', months = 35, fine = 10500, color = 'red'},
    }
}


Config.PoliceJobs = {
    ['police'] = true,
    ['lspd'] = true,
    ['bcso'] = true,
    ['sast'] = true,
    ['sasp'] = true,
    ['doc'] = true,
    ['lssd'] = true,
    ['sapr'] = true,
    ['pa'] = true -- yucky
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = true
}

Config.DojJobs = {
    ['lawyer'] = true,
    ['judge'] = true
}

-- Leave my hacky code alone ya goblins
Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end
-- Leave my hacky code alone ya goblins

Config.LogPerms = {
	['ambulance'] = {
		[8] = true,
	},
	['police'] = {
		[14] = true,
	},
}

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end

-- this is a hack, because the qb-menu in qb-policejob populates an impound location and passed it through to the event.
-- if this impound locations are changed in qb-policejob, they must also be changed here.
Config.ImpoundLocations = {
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}
